import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../core/build_config.dart';
import '../core/pubspec_parser.dart';
import '../utils/console.dart';

/// Command to generate fluttercraft.yaml configuration file
class GenCommand extends Command<int> {
  final Console console;

  GenCommand({Console? console}) : console = console ?? Console() {
    argParser.addFlag(
      'force',
      abbr: 'f',
      help: 'Overwrite existing fluttercraft.yaml',
      negatable: false,
    );
  }

  @override
  String get name => 'gen';

  @override
  String get description => 'Generate fluttercraft.yaml configuration file';

  @override
  Future<int> run() async {
    final force = argResults?['force'] == true;
    final projectRoot = Directory.current.path;
    final configPath = p.join(projectRoot, 'fluttercraft.yaml');
    final configFile = File(configPath);

    // Check if file exists
    if (await configFile.exists() && !force) {
      console.warning('fluttercraft.yaml already exists.');
      console.info('Use --force to overwrite.');
      return 1;
    }

    // Load pubspec to get app name and version
    final pubspecParser = PubspecParser(projectRoot: projectRoot);
    final pubspecInfo = await pubspecParser.parse();

    final appName = pubspecInfo?.name ?? 'app';
    final buildName = pubspecInfo?.buildName ?? '1.0.0';
    final buildNumber = pubspecInfo?.buildNumber ?? '1';

    // Detect FVM version from .fvmrc
    final fvmVersion = BuildConfig.detectFvmVersion(projectRoot);

    // Detect Shorebird app_id from shorebird.yaml
    final shorebirdAppId = BuildConfig.detectShorebirdAppId(projectRoot);

    // Generate config content
    final content = _generateConfigContent(
      appName: appName,
      buildName: buildName,
      buildNumber: buildNumber,
      fvmVersion: fvmVersion,
      shorebirdAppId: shorebirdAppId,
    );

    // Write file
    await configFile.writeAsString(content);

    console.success('Generated fluttercraft.yaml');
    console.info('Location: $configPath');
    console.info('App name: $appName');
    console.info('Version: $buildName+$buildNumber');
    if (fvmVersion != null) {
      console.info('FVM version: $fvmVersion (auto-detected)');
    }
    if (shorebirdAppId != null) {
      console.info('Shorebird app_id: $shorebirdAppId (auto-detected)');
    }

    return 0;
  }

  String _generateConfigContent({
    required String appName,
    required String buildName,
    required String buildNumber,
    String? fvmVersion,
    String? shorebirdAppId,
  }) {
    return '''# fluttercraft.yaml - Build Configuration
# Generated by fluttercraft CLI

# ══════════════════════════════════════════════════════════════════════════════
# BASE BUILD CONFIGURATION (anchor for inheritance)
# ══════════════════════════════════════════════════════════════════════════════
build_defaults: &build_defaults
  # App identifier (from pubspec or override here)
  app_name: $appName

  # Semantic version (x.y.z)
  name: $buildName
  # Build number (integer)
  number: $buildNumber
  # Build type: aab | apk | ipa | app
  type: aab
  # Main entry point
  target: lib/main.dart

  # ────────────────────────────────────────────────────────────────────────────
  # Dart Define - Always applied when should_add_dart_define = true
  # ────────────────────────────────────────────────────────────────────────────
  global_dart_define:
    APP_NAME: $appName

  # Flavor/build-specific dart defines (merged with global)
  dart_define: {}

  # ────────────────────────────────────────────────────────────────────────────
  # Build Flags
  # ────────────────────────────────────────────────────────────────────────────
  flags:
    # Use dart-define (combines global_dart_define + dart_define)
    should_add_dart_define: false
    # Run flutter clean before build
    should_clean: false
    # Run build_runner before build
    should_build_runner: false

# ══════════════════════════════════════════════════════════════════════════════
# ACTIVE BUILD CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
build:
  <<: *build_defaults

  # Active flavor: null | dev | staging | prod
  # If set, overrides from flavors section are applied
  flavor: null

# ══════════════════════════════════════════════════════════════════════════════
# FLAVOR OVERRIDES
# Each flavor can override: name, number, flags, dart_define
# ══════════════════════════════════════════════════════════════════════════════
flavors:
  dev:
    flags:
      should_add_dart_define: true
    dart_define:
      IS_DEV: true
      LOG_LEVEL: debug

  staging:
    name: $buildName-rc
    flags:
      should_add_dart_define: true
      should_clean: true
    dart_define:
      IS_STAGING: true

  prod:
    flags:
      should_add_dart_define: true
      should_clean: true
      should_build_runner: true
    dart_define:
      IS_PROD: true

# ══════════════════════════════════════════════════════════════════════════════
# ENVIRONMENT TOOLS (global only - not overridable by flavors)
# ══════════════════════════════════════════════════════════════════════════════
environments:
  # FVM integration
  fvm:
    enabled: ${fvmVersion != null ? 'true' : 'false'}
    # Pinned Flutter version (auto-detected from .fvmrc if null)
    version: ${fvmVersion ?? 'null'}

  # Shorebird integration
  shorebird:
    enabled: ${shorebirdAppId != null ? 'true' : 'false'}
    # App ID (auto-detected from shorebird.yaml)
    app_id: ${shorebirdAppId ?? 'null'}
    # @read-only [build:type] - Artifact type derived from build.type
    artifact: null
    # Skip confirmation prompts (maps to --no-confirm)
    no_confirm: true

  # Bundletool (AAB → APK conversion)
  bundletool:
    # Path to bundletool.jar (optional)
    path: null
    # Path to key.properties file
    keystore: android/key.properties

  # Disable colors in console output
  no_color: false

# ══════════════════════════════════════════════════════════════════════════════
# OUTPUT PATHS
# ══════════════════════════════════════════════════════════════════════════════
paths:
  # Output directory for build artifacts
  # Note: if flavor is set, output becomes dist/<flavor>/
  output: dist

# ══════════════════════════════════════════════════════════════════════════════
# CUSTOM COMMAND ALIASES
# ══════════════════════════════════════════════════════════════════════════════
alias:
  gen-icon:
    cmds:
      - fvm flutter pub get
      - fvm flutter pub run flutter_launcher_icons
  brn:
    cmds:
      - fvm flutter pub get
      - fvm flutter packages pub run build_runner build --delete-conflicting-outputs
''';
  }
}
