import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../core/build_config.dart';
import '../core/pubspec_parser.dart';
import '../utils/console.dart';

/// Command to generate fluttercraft.yaml configuration file
class GenCommand extends Command<int> {
  final Console console;

  GenCommand({Console? console}) : console = console ?? Console() {
    argParser.addFlag(
      'force',
      abbr: 'f',
      help: 'Overwrite existing fluttercraft.yaml',
      negatable: false,
    );
  }

  @override
  String get name => 'gen';

  @override
  String get description => 'Generate fluttercraft.yaml configuration file';

  @override
  Future<int> run() async {
    final force = argResults?['force'] == true;
    final projectRoot = Directory.current.path;
    final configPath = p.join(projectRoot, 'fluttercraft.yaml');
    final configFile = File(configPath);

    // Check if file exists
    if (await configFile.exists() && !force) {
      console.warning('fluttercraft.yaml already exists.');
      console.info('Use --force to overwrite.');
      return 1;
    }

    // Load pubspec to get app name and version
    final pubspecParser = PubspecParser(projectRoot: projectRoot);
    final pubspecInfo = await pubspecParser.parse();

    final appName = pubspecInfo?.name ?? 'app';
    final buildName = pubspecInfo?.buildName ?? '1.0.0';
    final buildNumber = pubspecInfo?.buildNumber ?? '1';

    // Detect FVM version from .fvmrc
    final fvmVersion = BuildConfig.detectFvmVersion(projectRoot);

    // Detect Shorebird app_id from shorebird.yaml
    final shorebirdAppId = BuildConfig.detectShorebirdAppId(projectRoot);

    // Generate config content
    final content = _generateConfigContent(
      appName: appName,
      buildName: buildName,
      buildNumber: buildNumber,
      fvmVersion: fvmVersion,
      shorebirdAppId: shorebirdAppId,
    );

    // Write file
    await configFile.writeAsString(content);

    console.success('Generated fluttercraft.yaml');
    console.info('Location: $configPath');
    console.info('App name: $appName');
    console.info('Version: $buildName+$buildNumber');
    if (fvmVersion != null) {
      console.info('FVM version: $fvmVersion (auto-detected)');
    }
    if (shorebirdAppId != null) {
      console.info('Shorebird app_id: $shorebirdAppId (auto-detected)');
    }

    return 0;
  }

  String _generateConfigContent({
    required String appName,
    required String buildName,
    required String buildNumber,
    String? fvmVersion,
    String? shorebirdAppId,
  }) {
    return '''# fluttercraft.yaml - Build Configuration
# Generated by fluttercraft CLI

# ──────────────────────────────────────────────
# App info (from pubspec or override here)
# ──────────────────────────────────────────────
app:
  name: $appName                # APPNAME - app identifier

# ──────────────────────────────────────────────
# Core build settings
# ──────────────────────────────────────────────
build:
  name: $buildName                # BUILD_NAME - semantic version
  number: $buildNumber                  # BUILD_NUMBER - build number
  type: aab                  # BUILD_TYPE - aab | apk | ipa | app
  flavor: null               # FLAVOR - dev | staging | prod | null
  target: lib/main.dart      # TARGET_DART - main entry point

# ──────────────────────────────────────────────
# Output & Input paths
# ──────────────────────────────────────────────
paths:
  output: dist               # OUTPUT_PATH - output directory
  env: ./.env                # ENV_PATH - env file path (optional)

# ──────────────────────────────────────────────
# Build flags
# ──────────────────────────────────────────────
flags:
  use_dart_define: false     # USE_DART_DEFINE
  need_clean: false          # NEED_CLEAN - run flutter clean before build
  need_build_runner: false   # NEED_BUILD_RUNNER - run build_runner

# ──────────────────────────────────────────────
# FVM integration
# ──────────────────────────────────────────────
fvm:
  enabled: true             # USE_FVM - use FVM for flutter commands
  version: ${fvmVersion ?? 'null'}              # FLUTTER_VERSION - pinned version (optional)

# ──────────────────────────────────────────────
# Shorebird integration
# ──────────────────────────────────────────────
shorebird:
  enabled: false             # USE_SHOREBIRD
  app_id: ${shorebirdAppId ?? 'null'}               # SHOREBIRD_APP_ID (auto-detected from shorebird.yaml)
  artifact: null             # SHOREBIRD_ARTIFACT - apk | aab
  auto_confirm: true         # SHOREBIRD_AUTO_CONFIRM --no-confirm

# ──────────────────────────────────────────────
# Bundletool (AAB → APK conversion)
# ──────────────────────────────────────────────
bundletool:
  path: null                 # BUNDLETOOL_PATH (optional)
  keystore: android/key.properties  # KEY_PROPERTIES_PATH

# ──────────────────────────────────────────────
# Custom command aliases
# ──────────────────────────────────────────────
alias:
  gen-icon:
    cmds:
      - fvm flutter pub get
      - fvm flutter pub run flutter_launcher_icons
  brn:
    cmds:
      - fvm flutter pub get
      - fvm flutter packages pub run build_runner build --delete-conflicting-outputs
''';
  }
}

